# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkowldIhXLoI0RJyPe40v0xlUuFt26BR
"""

import subprocess
import os
import sys
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Draw
import tempfile

def install_xtb():
    """Install xTB in Google Colab"""
    print("Installing xTB...")
    try:
        # Install xTB using conda
        subprocess.run([
            "wget", "https://github.com/grimme-lab/xtb/releases/download/v6.6.0/xtb-6.6.0-linux-x86_64.tar.xz"
        ], check=True)
        subprocess.run(["tar", "-xf", "xtb-6.6.0-linux-x86_64.tar.xz"], check=True)
        subprocess.run(["cp", "-r", "xtb-6.6.0", "/usr/local/"], check=True)
        subprocess.run(["ln", "-sf", "/usr/local/xtb-6.6.0/bin/xtb", "/usr/local/bin/xtb"], check=True)
        subprocess.run(["ln", "-sf", "/usr/local/xtb-6.6.0/lib", "/usr/local/lib/xtb"], check=True)

        # Add to PATH
        os.environ['PATH'] = '/usr/local/xtb-6.6.0/bin:' + os.environ['PATH']
        os.environ['XTBPATH'] = '/usr/local/xtb-6.6.0'

        print("✓ xTB установлен успешно!")
        return True
    except Exception as e:
        print(f"✗ ошибка установки xTB: {e}")
        return False
def check_xtb_installation():
    """Check if xTB is installed and available"""
    try:
        result = subprocess.run(["which", "xtb"], capture_output=True, text=True)
        if result.returncode == 0:
            print("✓ xTB уже установлен!")
            return True
        else:
            print("xTB не найден, установка...")
            return install_xtb()
    except Exception as e:
        print(f"Error checking xTB installation: {e}")
        return install_xtb()

def smiles_to_xtb_calculation(smiles, calculation_type='sp', charge=0, spin=1,
                            solvent=None, output_dir="."):
    """
    Convert SMILES to 3D geometry and run xtb calculations

    Parameters:
    - smiles: SMILES string
    - calculation_type: 'sp' for single-point, 'opt' for optimization, 'freq' for frequency
    - charge: molecular charge
    - spin: spin multiplicity (1 for singlet, 2 for doublet, etc.)
    - solvent: solvent for GBSA model (e.g., 'water', 'methanol')
    - output_dir: output directory
    """

    # First check if xTB is installed
    if not check_xtb_installation():
        raise RuntimeError("xTB is not available. Please install it manually.")

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Generate molecule from SMILES
    print(f"Обработка SMILES: {smiles}")
    mol = Chem.MolFromSmiles(smiles)

    if mol is None:
        raise ValueError(f"Плохо написанный SMILES: {smiles}")

    # Add hydrogens
    mol = Chem.AddHs(mol)

    # Generate 3D coordinates
    print("Генерация 3D координат...")
    AllChem.EmbedMolecule(mol, randomSeed=42)

    # Optimize with MMFF94
    print("Оптимизация с MMFF94...")
    AllChem.MMFFOptimizeMolecule(mol)

    # Generate molecule name from SMILES
    mol_name = smiles.replace('/', '_').replace('\\', '_')[:20]

    # Save as XYZ file
    xyz_file = os.path.join(output_dir, f"{mol_name}.xyz")

    # Write XYZ file
    with open(xyz_file, 'w') as f:
        f.write(f"{mol.GetNumAtoms()}\n")
        f.write(f"Сгенерированно из SMILES: {smiles}\n")

        conf = mol.GetConformer()
        for i, atom in enumerate(mol.GetAtoms()):
            pos = conf.GetAtomPosition(i)
            symbol = atom.GetSymbol()
            f.write(f"{symbol} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}\n")

    print(f"Геметрия сохранена в: {xyz_file}")

    # Save molecule image
    img_file = os.path.join(output_dir, f"{mol_name}.png")
    img = Draw.MolToImage(mol, size=(300, 300))
    img.save(img_file)
    print(f"Изображение молекулы сохранено в : {img_file}")

    # Display molecule image in Colab
    try:
        from IPython.display import display
        display(img)
    except:
        pass

    # Run xtb calculations
    if calculation_type == 'sp':
        return run_xtb_single_point(xyz_file, charge, spin, solvent, output_dir)
    elif calculation_type == 'opt':
        return run_xtb_optimization(xyz_file, charge, spin, solvent, output_dir)
    elif calculation_type == 'freq':
        return run_xtb_frequency(xyz_file, charge, spin, solvent, output_dir)
    else:
        raise ValueError("calculation_type must be 'sp', 'opt', or 'freq'")

def run_xtb_single_point(xyz_file, charge=0, spin=1, solvent=None, output_dir="."):
    """Run single-point energy calculation"""
    print("Начинаем single-point рассчет энергии...")

    # Use list-based command for better security and compatibility
    cmd = ["xtb", os.path.basename(xyz_file), "--sp", "--chrg", str(charge), "--uhf", str(spin-1)]

    if solvent:
        # Fix potential typo in solvent name
        if solvent.lower() == "mathanol":
            solvent = "methanol"
            print(f"Note: Changed solvent from 'mathanol' to 'methanol'")
        cmd.extend(["--gbsa", solvent])

    print(f"Command: {' '.join(cmd)}")

    # Change to output directory and run command
    original_dir = os.getcwd()
    os.chdir(output_dir)

    try:
        result = subprocess.run(cmd, capture_output=True, text=True)

        # Save output
        log_file = "single_point.log"
        with open(log_file, "w") as f:
            f.write(result.stdout)

        if result.returncode == 0:
            print("✓ Single-point рассчеты завершены!")
            print(f"Результат сохранён в: {log_file}")
            return parse_xtb_output(result.stdout)
        else:
            print("✗ Single-point calculation failed!")
            print(f"Error: {result.stderr}")
            # Also print the full output for debugging
            print("Full output:")
            print(result.stdout)
            return None
    finally:
        os.chdir(original_dir)

def run_xtb_optimization(xyz_file, charge=0, spin=1, solvent=None, output_dir="."):
    """Run geometry optimization"""
    print("Running geometry optimization...")

    cmd = ["xtb", os.path.basename(xyz_file), "--opt", "--chrg", str(charge), "--uhf", str(spin-1)]

    if solvent:
        if solvent.lower() == "mathanol":
            solvent = "methanol"
            print(f"Note: Changed solvent from 'mathanol' to 'methanol'")
        cmd.extend(["--gbsa", solvent])

    print(f"Command: {' '.join(cmd)}")

    # Change to output directory and run command
    original_dir = os.getcwd()
    os.chdir(output_dir)

    try:
        result = subprocess.run(cmd, capture_output=True, text=True)

        # Save output
        log_file = "optimization.log"
        with open(log_file, "w") as f:
            f.write(result.stdout)

        if result.returncode == 0:
            print("✓ Optimization completed!")
            optimized_file = "xtbopt.xyz"
            if os.path.exists(optimized_file):
                print(f"Optimized geometry: {optimized_file}")
            print(f"Output saved to: {log_file}")
            return parse_xtb_output(result.stdout)
        else:
            print("✗ Optimization failed!")
            print(f"Error: {result.stderr}")
            print("Full output:")
            print(result.stdout)
            return None
    finally:
        os.chdir(original_dir)

def run_xtb_frequency(xyz_file, charge=0, spin=1, solvent=None, output_dir="."):
    """Run frequency calculation"""
    print("Running frequency calculation...")

    cmd = ["xtb", os.path.basename(xyz_file), "--hess", "--chrg", str(charge), "--uhf", str(spin-1)]

    if solvent:
        if solvent.lower() == "mathanol":
            solvent = "methanol"
            print(f"Note: Changed solvent from 'mathanol' to 'methanol'")
        cmd.extend(["--gbsa", solvent])

    print(f"Command: {' '.join(cmd)}")

    # Change to output directory and run command
    original_dir = os.getcwd()
    os.chdir(output_dir)

    try:
        result = subprocess.run(cmd, capture_output=True, text=True)

        # Save output
        log_file = "frequency.log"
        with open(log_file, "w") as f:
            f.write(result.stdout)

        if result.returncode == 0:
            print("✓ Frequency calculation completed!")
            print(f"Output saved to: {log_file}")
            return parse_xtb_output(result.stdout)
        else:
            print("✗ Frequency calculation failed!")
            print(f"Error: {result.stderr}")
            print("Full output:")
            print(result.stdout)
            return None
    finally:
        os.chdir(original_dir)

def parse_xtb_output(output):
    """Parse xtb output to extract total energy and HOMO-LUMO gap"""
    results = {}

    lines = output.split('\n')

    for i, line in enumerate(lines):
        # Parse TOTAL ENERGY (from the box at the end)
        if 'TOTAL ENERGY' in line:
            try:
                # Extract energy value from lines like:
                # "| TOTAL ENERGY              -11.393351577127 Eh   |"
                parts = line.split()
                for j, part in enumerate(parts):
                    if part == 'ENERGY':
                        energy_str = parts[j+1]  # Should be the energy value
                        results['total_energy'] = float(energy_str)
                        results['energy_units'] = 'Eh'  # Hartree
                        break
            except (ValueError, IndexError):
                pass

        # Parse HOMO-LUMO GAP (from the box at the end)
        elif 'HOMO-LUMO GAP' in line:
            try:
                # Extract gap value from lines like:
                # "| HOMO-LUMO GAP              12.525947406591 eV   |"
                parts = line.split()
                for j, part in enumerate(parts):
                    if part == 'GAP':
                        gap_str = parts[j+1]  # Should be the gap value
                        results['homo_lumo_gap'] = float(gap_str)
                        results['gap_units'] = 'eV'
                        break
            except (ValueError, IndexError):
                pass

        # Alternative parsing for HOMO-LUMO gap from the orbital section
        elif 'HL-Gap' in line:
            try:
                # Extract from lines like:
                # "HL-Gap            0.4603201 Eh           12.5259 eV"
                parts = line.split()
                # The gap in eV is usually the last numeric value
                for part in reversed(parts):
                    try:
                        gap_value = float(part)
                        # Check if this is likely the eV value (reasonable range for gaps)
                        if 0.1 < gap_value < 50.0:
                            results['homo_lumo_gap'] = gap_value
                            results['gap_units'] = 'eV'
                            break
                    except ValueError:
                        continue
            except (ValueError, IndexError):
                pass

        # Alternative parsing for total energy (from earlier in the output)
        elif 'total energy' in line.lower() and 'total_energy' not in results:
            try:
                # Extract from lines like: "total energy  :        -11.393351577127 Eh"
                parts = line.split()
                for j, part in enumerate(parts):
                    if part.lower() == 'energy':
                        energy_str = parts[j+2]  # Usually two parts after "energy"
                        results['total_energy'] = float(energy_str)
                        results['energy_units'] = parts[j+3]
                        break
            except (ValueError, IndexError):
                pass

    # If we found both values, also calculate the gap in Hartree for consistency
    if 'total_energy' in results and 'homo_lumo_gap' in results:
        # Convert eV to Hartree (1 eV = 0.0367493 Hartree)
        results['homo_lumo_gap_hartree'] = results['homo_lumo_gap'] * 0.0367493

    return results

def run_calculation_interactive(smiles = None):
    """Interactive function for Google Colab - gets input from user"""

    print("=" * 60)
    print("xTB Calculation from SMILES")
    print("=" * 60)
    
    # First check and install xTB if needed
    if not check_xtb_installation():
        print("Failed to install xTB. Please install it manually.")
        return

    # Interactive input for Colab
    # smiles = input("Введите SMILES строку (например, CCO для этанола): ").strip()

    calculation = 'sp'

    charge = 0

    spin = 1

    # solvent = input("Solvent for GBSA model (e.g., water, methanol) [optional]: ").strip()
    # if not solvent:
    solvent = None

    
    output_dir = "./output/" + str(smiles) + "/"
    print (f"Результаты рассчета будут сохранены в {output_dir}")

    try:
        # Run the calculation
        results = smiles_to_xtb_calculation(
            smiles=smiles,
            calculation_type=calculation,
            charge=charge,
            spin=spin,
            solvent=solvent,
            output_dir=output_dir
        )

        # Print results
        if results:
            print("\n" + "="*50)
            print("Рассчитанные результаты")
            print("="*50)
            for key, value in results.items():
                print(f"{key}: {value}")

            # Create a simple summary
            print("\n" + "="*50)
            print("SUMMARY")
            print("="*50)
            if 'total_energy' in results:
                print(f"Общая энергия: {results['total_energy']:.6f} {results.get('energy_units', 'Eh')}")
            if 'homo_lumo_gap' in results:
                print(f"HOMO-LUMO переход: {results['homo_lumo_gap']:.4f} {results.get('gap_units', 'eV')}")
            return results
        else:
            print("No results obtained from calculation")

    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()

# For Google Colab compatibility
if __name__ == "__main__":
    # Check if we're in a notebook environment
    try:
        from IPython import get_ipython
        if 'IPKernelApp' in get_ipython().config:
            print("Running in Jupyter/Colab environment")
            # You can call run_calculation_interactive() directly in Colab
    except:
        print("Running in standard Python environment")
        run_calculation_interactive()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

def gap_to_wavenumber_and_color(gap_hartree):
    """
    Convert HOMO-LUMO gap from Hartree to wavenumber (cm⁻¹) and approximate color
    """
    # Constants for conversion
    HARTREE_TO_JOULE = 4.3597447222071e-18
    PLANCK_CONSTANT = 6.62607015e-34
    SPEED_OF_LIGHT = 2.99792458e10  # cm/s

    # Convert Hartree to Joules
    gap_joules = gap_hartree * HARTREE_TO_JOULE

    # Convert energy to frequency (Hz)
    frequency_hz = gap_joules / PLANCK_CONSTANT

    # Convert frequency to wavenumber (cm⁻¹)
    wavenumber_cm1 = frequency_hz / SPEED_OF_LIGHT

    # Convert wavenumber to wavelength (nm)
    if wavenumber_cm1 > 0:
        wavelength_nm = 1e7 / wavenumber_cm1
    else:
        wavelength_nm = 0

    # Get RGB color (handle IR/UV regions properly)
    rgb_color, color_info = get_color_with_extended_range(wavelength_nm)

    return {
        'gap_hartree': gap_hartree,
        'gap_ev': gap_hartree / 0.0367493,
        'wavenumber_cm1': wavenumber_cm1,
        'wavelength_nm': wavelength_nm,
        'rgb_color': rgb_color,
        'color_region': color_info['region'],
        'visible': color_info['visible']
    }

def get_color_with_extended_range(wavelength_nm):
    """
    Get color with proper handling of IR and UV regions
    """
    if wavelength_nm <= 0:
        return (0, 0, 0), {'region': 'Invalid', 'visible': False}

    # Extended wavelength ranges with meaningful colors
    if wavelength_nm < 10:  # Gamma rays, X-rays
        return (128, 0, 128), {'region': 'Gamma/X-ray', 'visible': False}
    elif 10 <= wavelength_nm < 200:  # Extreme UV
        return (75, 0, 130), {'region': 'Extreme UV', 'visible': False}
    elif 200 <= wavelength_nm < 380:  # UV
        # Gradient from violet to blue in UV
        factor = (wavelength_nm - 200) / (380 - 200)
        r = int(128 * factor)
        g = 0
        b = int(128 + 127 * factor)
        return (r, g, b), {'region': 'UV', 'visible': False}
    elif 380 <= wavelength_nm <= 780:  # Visible
        rgb = wavelength_to_rgb_piecewise(wavelength_nm)
        return rgb, {'region': 'Visible', 'visible': True}
    elif 780 < wavelength_nm <= 2500:  # Near IR
        # Gradient from red to black in IR
        factor = 1.0 - min(1.0, (wavelength_nm - 780) / (2500 - 780))
        r = int(255 * factor)
        g = 0
        b = 0
        return (r, g, b), {'region': 'Near IR', 'visible': False}
    elif 2500 < wavelength_nm <= 25000:  # Mid IR
        # Dark red to black
        factor = 1.0 - min(1.0, (wavelength_nm - 2500) / (25000 - 2500))
        r = int(128 * factor)
        g = 0
        b = 0
        return (r, g, b), {'region': 'Mid IR', 'visible': False}
    else:  # Far IR, microwave, radio
        return (64, 64, 64), {'region': 'Far IR/Radio', 'visible': False}

def wavelength_to_rgb_piecewise(wavelength_nm):
    """Convert wavelength to RGB (visible spectrum only)"""
    if wavelength_nm < 380 or wavelength_nm > 780:
        return (0, 0, 0)

    wavelength = float(wavelength_nm)

    if wavelength >= 380 and wavelength <= 440:
        r = -(wavelength - 440) / (440 - 380)
        g = 0.0
        b = 1.0
    elif wavelength >= 440 and wavelength <= 490:
        r = 0.0
        g = (wavelength - 440) / (490 - 440)
        b = 1.0
    elif wavelength >= 490 and wavelength <= 510:
        r = 0.0
        g = 1.0
        b = -(wavelength - 510) / (510 - 490)
    elif wavelength >= 510 and wavelength <= 580:
        r = (wavelength - 510) / (580 - 510)
        g = 1.0
        b = 0.0
    elif wavelength >= 580 and wavelength <= 645:
        r = 1.0
        g = -(wavelength - 645) / (645 - 580)
        b = 0.0
    elif wavelength >= 645 and wavelength <= 780:
        r = 1.0
        g = 0.0
        b = 0.0
    else:
        r = 0.0
        g = 0.0
        b = 0.0

    # Intensity correction
    if wavelength >= 380 and wavelength < 420:
        factor = 0.3 + 0.7 * (wavelength - 380) / (420 - 380)
    elif wavelength >= 420 and wavelength < 701:
        factor = 1.0
    elif wavelength >= 701 and wavelength <= 780:
        factor = 0.3 + 0.7 * (780 - wavelength) / (780 - 700)
    else:
        factor = 0.0

    r = int(255 * r * factor)
    g = int(255 * g * factor)
    b = int(255 * b * factor)

    return (max(0, min(255, r)), max(0, min(255, g)), max(0, min(255, b)))

def display_single_color(rgb, color_name="Color", size=(5, 2), save_path = None):
    """
    Display a single color with RGB values
    """
    print (f"Твой RGB вектор - {rgb}")
    # Create figure
    fig, ax = plt.subplots(1, 1, figsize=size)

    # Convert RGB to 0-1 range for matplotlib
    rgb_normalized = [x/255 for x in rgb]

    # Create a simple rectangle with the color
    ax.add_patch(plt.Rectangle((0, 0), 1, 1, color=rgb_normalized))

    # Set up the plot
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_aspect('equal')
    ax.axis('off')

    # Add text with RGB values
    # ax.text(0.5, 0.5, f'Твой RGB вектор цвета - {rgb}',
    #        ha='center', va='center', fontsize=12,
    #        color='white' if sum(rgb) < 380 else 'black',
    #        weight='bold')
    ax.set_title(f'Твой RGB вектор цвета - {rgb}', 
             fontsize=10,  # Размер шрифта заголовка
             color='black',  # Цвет заголовка
             weight='bold',  # Жирность
             pad=20)  # Отступ от графика

    plt.tight_layout()

    if save_path:
        # Create directory if it doesn't exist
        # os.makedirs(os.path.dirname(save_path) if os.path.dirname(save_path) else '.', exist_ok=True)
        # Save the figure
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Картинка сохранена в: {save_path}")

    plt.show()

def save_name_tuple(name, tuple_data, filename="data.txt"):
    """
    Сохраняет пару name:tuple в файл
    """
    try:
        # Проверяем существование файла
        if not os.path.exists(filename):
            print(f"Файл '{filename}' не существует. Создаем новый.")
        
        with open(filename, 'a', encoding='utf-8') as file:
            file.write(f"{name}: {tuple_data}\n")
        print(f"Сохранено: {name}: {tuple_data}")
    except Exception as e:
        print(f"Ошибка сохранения: {e}")

def parse_colors(filename="colors.txt"):
    """
    Парсит файл и возвращает словарь {имя: кортеж_RGB}
    Гарантирует, что все значения - кортежи из 3 чисел
    """
    colors_dict = {}
    try:
        with open(filename, 'r', encoding='utf-8') as file:
            for line_num, line in enumerate(file, 1):
                line = line.strip()
                if line and ':' in line:
                    name, tuple_str = line.split(':', 1)
                    name = name.strip()
                    tuple_str = tuple_str.strip()
                    
                    try:
                        # Парсим кортеж
                        parsed_data = ast.literal_eval(tuple_str)
                        
                        # Преобразуем в tuple если нужно
                        if not isinstance(parsed_data, tuple):
                            parsed_data = tuple(parsed_data)
                        
                        # Проверяем, что это кортеж из 3 чисел
                        if (isinstance(parsed_data, tuple) and 
                            len(parsed_data) == 3 and 
                            all(isinstance(x, (int, float)) for x in parsed_data)):
                            
                            # Конвертируем в целые числа если нужно
                            rgb_tuple = tuple(int(x) for x in parsed_data)
                            colors_dict[name] = rgb_tuple
                        else:
                            print(f"Пропущена строка {line_num}: неверный формат RGB")
                            
                    except (ValueError, SyntaxError) as e:
                        print(f"Ошибка парсинга в строке {line_num}: {e}")
                        continue
                        
        return colors_dict
    except FileNotFoundError:
        print(f"Файл {filename} не найден")
        return {}
    except Exception as e:
        print(f"Ошибка чтения: {e}")
        return {}
        
log_file_name = os.path.join("./output/", "log")

def homo_lumo_color():
    smiles = input("Введите SMILES строку (например, CCO для этанола): ").strip()
    res = run_calculation_interactive(smiles)
    re = gap_to_wavenumber_and_color(res["homo_lumo_gap_hartree"])

    save_name_tuple(smiles, re['rgb_color'], filename = log_file_name)
    
    display_single_color(re['rgb_color'], save_path = os.path.join("./output/", smiles))
    return re['rgb_color']
# -*- coding: utf-8 -*-
"""Stable Diffusion с выбором моделей"""

import torch
import time
import matplotlib.pyplot as plt
from google.colab import files
import gc

# Очистка памяти
if torch.cuda.is_available():
    torch.cuda.empty_cache()
gc.collect()

# Список доступных моделей
MODELS = {
    "4": {
        "name": "DreamShaper (УНИВЕРСАЛЬНАЯ)",
        "id": "lykon/dreamshaper-8",
        "type": "stable_diffusion"
    }
}

def load_model(model_choice="1"):
    """Загрузка выбранной модели"""
    model_info = MODELS[model_choice]
    print(f"🚀 Загрузка: {model_info['name']}")
    print(f"📁 Модель: {model_info['id']}")

    try:
        from diffusers import StableDiffusionPipeline

        pipe = StableDiffusionPipeline.from_pretrained(
            model_info["id"],
            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            safety_checker=None,
            requires_safety_checker=False
        )

        if torch.cuda.is_available():
            pipe = pipe.to("cuda")
            pipe.enable_attention_slicing()
            print("✅ Модель на GPU с оптимизацией")
        else:
            pipe = pipe.to("cpu")
            print("⚠️  Модель на CPU - будет медленно")

        print(f"✅ {model_info['name']} загружена!")
        return pipe

    except Exception as e:
        print(f"❌ Ошибка загрузки {model_info['name']}: {e}")
        print("🔄 Пробуем загрузить базовую модель...")

        # Пробуем базовую модель как запасной вариант
        from diffusers import StableDiffusionPipeline
        pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
        pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")
        return pipe



# Глобальная переменная для текущей модели
pipe = None

def initialize_generator():
    """Инициализация генератора с выбором модели"""
    global pipe

    while True:
        choice = "4".strip()

        if choice in MODELS:
            pipe = load_model(choice)
            if pipe is not None:
                return
        else:
            print("❌ Неверный выбор. Попробуйте снова.")

def generate_with_progress(prompt, steps=20):
    """Генерация с прогресс-баром"""
    global pipe

    if pipe is None:
        print("❌ Модель не загружена! Инициализируйте сначала.")
        return None

    print(f"🎨 Запрос: '{prompt}'")
    print(f"🔢 Шагов: {steps}")
    print("⏳ Генерация...", end=" ")

    start_time = time.time()

    # Генерируем изображение
    result = pipe(
        prompt=prompt,
        num_inference_steps=steps,
        guidance_scale=7.5,
        width=512,
        height=512
    )

    end_time = time.time()
    generation_time = end_time - start_time

    print(f"✅ Завершено за {generation_time:.1f} секунд")

    # Сохранение с именем от пользователя
    filename = input("💾 Введите название файла (без .png): ").strip()
    if not filename:
        filename = f"image_{int(time.time())}"

    filename += ".png"
    result.images[0].save(filename)
    print(f"💾 Сохранено как: {filename}")

    return result.images[0]

# Примеры промптов для разных моделей
EXAMPLE_PROMPTS = {
    "4": [
        "фэнтезийный пейзаж с драконом и замком, эпичное освещение",
        "аниме девушка с фиолетовыми волосами в магическом лесу",
        "киберпанк улица ночью, дождь, неоновая реклама"
    ]
}

def main_interface():
    """Главный интерфейс программы"""
    global pipe

    # Инициализация модели
    initialize_generator()

    current_model = None
    for key, model in MODELS.items():
        if "dreamshaper" in model["id"].lower() and isinstance(pipe, type(pipe)):
            current_model = key
            break

    if current_model is None:
        current_model = "1"

    print(f"\n✨ Текущая модель: {MODELS[current_model]['name']}")

    while True:
        print("\n" + "="*40)
        print("🎨 ГЛАВНОЕ МЕНЮ")
        print("="*40)

        choice = input(
            "Выберите действие:\n"
            "1 - Сгенерировать изображение\n"
            "2 - Показать примеры для текущей модели\n"
            "3 - Выход\n"
            "> "
        ).strip()

        if choice == "1":
            prompt = input("📝 Введите описание изображения: ").strip()
            if not prompt:
                print("❌ Описание не может быть пустым")
                continue

            try:
                steps = int(input("🔢 Количество шагов (от 15): ") or "20")
                steps = max(15, steps)
            except:
                steps = 20

            image = generate_with_progress(prompt, steps)

            if image:
                # Показываем результат
                plt.figure(figsize=(10, 8))
                plt.imshow(image)
                plt.axis('off')
                plt.title(f'"{prompt}"', pad=20)
                plt.tight_layout()
                plt.show()



        elif choice == "2":
            print(f"\n🚀 Примеры для {MODELS[current_model]['name']}:")
            for i, example in enumerate(EXAMPLE_PROMPTS[current_model], 1):
                print(f"{i}. {example}")


        elif choice == "3":
            print("👋 До свидания!")
            break

        else:
            print("❌ Неверный выбор")

import numpy as np
from PIL import Image

def quick_color_restore(image_path, colors_to_restore):
    """
    Быстрое восстановление нескольких цветов за один раз
    
    Args:
        image_path (str): путь к изображению
        colors_to_restore (dict): словарь с цветами в формате имя:кортеж_RGB
    """
    original_img = Image.open(image_path).convert('RGB')
    img_array = np.array(original_img)
    
    # Создаем черно-белую версию
    bw_array = np.dot(img_array[...,:3], [0.0, 0.0, 0.0])
    bw_array = np.stack([bw_array, bw_array, bw_array], axis=-1).astype(np.uint8)
    result_array = bw_array.copy()
    
    # Восстанавливаем все указанные цвета
    total_mask = np.zeros(img_array.shape[:2], dtype=bool)
    
    # Проверяем тип данных и обрабатываем соответствующим образом
    if isinstance(colors_to_restore, dict):
        # Если передан словарь
        color_items = colors_to_restore.items()
    elif isinstance(colors_to_restore, (list, tuple)):
        # Если передан список или кортеж, преобразуем в словарь
        colors_dict = {}
        for i, item in enumerate(colors_to_restore):
            if isinstance(item, dict):
                colors_dict.update(item)
        color_items = colors_dict.items()
    else:
        raise ValueError("colors_to_restore должен быть словарем или списком/кортежем словарей")
    Smiles = []
    # Пробегаемся по всем элементам
    for color_name, target_rgb in color_items:
        # Преобразуем в numpy array
        target_rgb = np.array(target_rgb)
        
        # Нормализуем векторы для косинусного сходства
        img_norm = np.linalg.norm(img_array, axis=2)
        target_norm = np.linalg.norm(target_rgb)
     
        # Скалярное произведение и косинусное сходство
        dot_product = np.dot(img_array, target_rgb)
        cosine_similarity = dot_product / (img_norm * target_norm + 1e-8)
        
        # Порог косинусного сходства
        mask = cosine_similarity > 0.9
        total_mask = total_mask | mask
        Smiles.append(color_name)
    # Применяем все маски
    result_array[total_mask] = img_array[total_mask].astype(np.uint8)
    result_img = Image.fromarray(result_array)
    print (f"Использованные SMILES : {Smiles}")
    print (f"Всего SMILES : {len(Smiles)}")
    return result_img
    
def painter(picture_path):
    color_data = parse_colors(log_file_name)
    quick_color_restore(picture_path, color_data)
